name: "DEMKit"
description: "Home Energy Management made difficult"
version: "1.0.0-beta1"
slug: "demkit"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
image: eldani/hass-demkit-addon:v1.0.0-beta1