name: "DEMKit"
description: "Home Energy Management made difficult"
version: "v1.0.0-beta16"
slug: "demkit"
init: false
#image: docker.io/eldani/image-{arch}-demkit-addon
arch:
  - aarch64
  - amd64
environment:
  DEMKIT_FOLDER: /app/demkit/example/offgridhouse_real
  DEMKIT_MODEL: realhouse_simulated
  DEMKIT_INFLUXPW: d1a2n3i4e5l6
  DEMKIT_LONGITUDE: 0.0
  DEMKIT_LATITUDE: 0.0
  DEMKIT_ALTITUDE: 0.0